version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      dockerfile: .docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - 8081:80
    networks:
      - laravel-network

  laravel-db:
    image: mysql:5.7
    container_name: laravel-db
    volumes:
      - .mysqldata:/var/lib/mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
